# Generated by Django 6.1.1 on 2026-09-09 19:05

from django.db import migrations

def seed_data(apps, schema_editor):
    Priorities = apps.get_model('helpdeskapp', 'Priorities')
    Settings = apps.get_model('helpdeskapp', 'Settings')

    Priorities.objects.create(priority='CRITICAL', sla=4)
    Priorities.objects.create(priority='HIGH', sla=8)
    Priorities.objects.create(priority='MEDIUM', sla=24)
    Priorities.objects.create(priority='LOW', sla=72)

    Settings.objects.create(days_until_closure=60)

class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0002_category_priorities_settings_report_comment_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
